tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "primary": "#630ed4",
                "on-primary": "#ffffff",
                "primary-container": "#7c3aed",
                "on-primary-container": "#ede0ff",
                "primary-fixed": "#eaddff",
                "primary-fixed-dim": "#d2bbff",
                "on-primary-fixed": "#25005a",
                "on-primary-fixed-variant": "#5a00c6",
                "inverse-primary": "#d2bbff",
                "secondary": "#855300",
                "on-secondary": "#ffffff",
                "secondary-container": "#fea619",
                "on-secondary-container": "#684000",
                "secondary-fixed": "#ffddb8",
                "secondary-fixed-dim": "#ffb95f",
                "on-secondary-fixed": "#2a1700",
                "on-secondary-fixed-variant": "#653e00",
                "tertiary": "#7d3d00",
                "on-tertiary": "#ffffff",
                "tertiary-container": "#a15100",
                "on-tertiary-container": "#ffe0cd",
                "tertiary-fixed": "#ffdcc6",
                "tertiary-fixed-dim": "#ffb784",
                "on-tertiary-fixed": "#301400",
                "on-tertiary-fixed-variant": "#713700",
                "surface": "#fef7ff",
                "surface-dim": "#dfd7e6",
                "surface-bright": "#fef7ff",
                "surface-container-lowest": "#ffffff",
                "surface-container-low": "#f9f1ff",
                "surface-container": "#f3ebfa",
                "surface-container-high": "#ede5f4",
                "surface-container-highest": "#e8dfee",
                "surface-variant": "#e8dfee",
                "on-surface": "#1d1a24",
                "on-surface-variant": "#4a4455",
                "inverse-surface": "#332f39",
                "inverse-on-surface": "#f6eefc",
                "outline": "#7b7487",
                "outline-variant": "#ccc3d8",
                "background": "#fef7ff",
                "on-background": "#1d1a24",
                "surface-tint": "#732ee4",
                "error": "#ba1a1a",
                "on-error": "#ffffff",
                "error-container": "#ffdad6",
                "on-error-container": "#93000a",
            },
            borderRadius: { DEFAULT: "0.25rem", lg: "0.5rem", xl: "0.75rem", full: "9999px" },
            spacing: {
                xs: "8px", sm: "16px", md: "24px", lg: "40px", xl: "64px",
                base: "4px", gutter: "24px", "container-max": "1200px"
            },
            fontFamily: {
                "body-md": ["Be Vietnam Pro"], "body-lg": ["Be Vietnam Pro"],
                "headline-lg": ["Be Vietnam Pro"], "headline-md": ["Be Vietnam Pro"],
                "headline-sm": ["Be Vietnam Pro"], "label-md": ["Be Vietnam Pro"],
                "display-lg": ["Be Vietnam Pro"]
            },
            fontSize: {
                "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
                "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
                "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
                "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
                "headline-sm": ["20px", { lineHeight: "1.4", fontWeight: "700" }],
                "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "700" }],
                "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
                "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
            }
        }
    }
}